### ISSUE TITLE
Attachment parsing error: binascii.Error: Incorrect padding

### ISSUE THREAD

**Issue by aktywnitu** [martinrusev/imbox#175]
Hi,
There are problem with attachment parsing in iterator:
Traceback (most recent call last):
  File "../ns_app/manage.py", line 15, in <module>
    execute_from_command_line(sys.argv)
  File "../venv3.5/lib/python3.5/site-packages/django/core/management/__init__.py", line 381, in execute_from_command_line
    utility.execute()
  File "../venv3.5/lib/python3.5/site-packages/django/core/management/__init__.py", line 375, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "../venv3.5/lib/python3.5/site-packages/django/core/management/base.py", line 316, in run_from_argv
    self.execute(*args, **cmd_options)
  File "../venv3.5/lib/python3.5/site-packages/django/core/management/base.py", line 353, in execute
    output = self.handle(*args, **options)
  File "../my_code/email_parser.py", line 177, in read_mails
    for uid, message in inbox_messages:
  File "../venv3.5/lib/python3.5/site-packages/imbox/messages.py", line 39, in _fetch_email_list
    yield uid, self._fetch_email(uid)
  File "../venv3.5/lib/python3.5/site-packages/imbox/messages.py", line 28, in _fetch_email
    parser_policy=self.parser_policy)
  File "../venv3.5/lib/python3.5/site-packages/imbox/parser.py", line 141, in fetch_email_by_uid
    email_object = parse_email(raw_email, policy=parser_policy)
  File "../venv3.5/lib/python3.5/site-packages/imbox/parser.py", line 196, in parse_email
    attachment = parse_attachment(part)
  File "../venv3.5/lib/python3.5/site-packages/imbox/parser.py", line 111, in parse_attachment
    name, value = decode_param(param)
  File "../venv3.5/lib/python3.5/site-packages/imbox/parser.py", line 78, in decode_param
    value = base64.decodebytes(code.encode())
  File "/usr/lib/python3.5/base64.py", line 553, in decodebytes
    return binascii.a2b_base64(s)
binascii.Error: Incorrect padding

**Comment by aktywnitu** [comment]
Pleas add binascii.Error exception handler.
