### ISSUE TITLE
Error receiving emails: UnicodeDecodeError

### ISSUE THREAD

**Issue by migelbd** [martinrusev/imbox#180]
`Traceback (most recent call last):
  File "manage.py", line 21, in <module>
    main()
  File "manage.py", line 17, in main
    execute_from_command_line(sys.argv)
  File "/usr/local/lib/python3.7/site-packages/django/core/management/__init__.py", line 401, in execute_from_command_line
    utility.execute()
  File "/usr/local/lib/python3.7/site-packages/django/core/management/__init__.py", line 395, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/usr/local/lib/python3.7/site-packages/django/core/management/base.py", line 328, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/usr/local/lib/python3.7/site-packages/django/core/management/base.py", line 369, in execute
    output = self.handle(*args, **options)
  File "/app/mail_checker/management/commands/check.py", line 19, in handle
    for msg in m.get_messages():
  File "/app/redmine_mail/mailbox.py", line 75, in get_messages
    for uid, message in unread_inbox_messages:
  File "/usr/local/lib/python3.7/site-packages/imbox/messages.py", line 39, in _fetch_email_list
    yield uid, self._fetch_email(uid)
  File "/usr/local/lib/python3.7/site-packages/imbox/messages.py", line 28, in _fetch_email
    parser_policy=self.parser_policy)
  File "/usr/local/lib/python3.7/site-packages/imbox/parser.py", line 141, in fetch_email_by_uid
    email_object = parse_email(raw_email, policy=parser_policy)
  File "/usr/local/lib/python3.7/site-packages/imbox/parser.py", line 196, in parse_email
    attachment = parse_attachment(part)
  File "/usr/local/lib/python3.7/site-packages/imbox/parser.py", line 111, in parse_attachment
    name, value = decode_param(param)
  File "/usr/local/lib/python3.7/site-packages/imbox/parser.py", line 79, in decode_param
    value = str_encode(value, encoding)
  File "/usr/local/lib/python3.7/site-packages/imbox/utils.py", line 7, in str_encode
    return str(value, encoding, errors)
UnicodeDecodeError: 'ascii' codec can't decode byte 0xd0 in position 0: ordinal not in range(128)`

**Comment by wesinator** [comment]
#77
