### ISSUE TITLE
invalid literal for int() with base 10: '' for clause

### ISSUE THREAD

**Issue by vncaragao** [martinrusev/imbox#227]
When my code runs **"for uid, message in all_inbox_messages:"**, shows **invalid literal for int() with base 10: '' for clause** Follows the log.

Exception in thread Thread-535:
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/threading.py", line 932, in _bootstrap_inner
    self.run()
  File "/usr/local/lib/python3.8/site-packages/flaskthreads/thread_helpers.py", line 191, in run
    super().run()
  File "/usr/local/lib/python3.8/threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/src/app/app/views/omnimail/controllers/ListEmails.py", line 33, in run
    Email.list(config)       
  File "/usr/src/app/app/entities/Email.py", line 68, in list
    for uid, message in all_inbox_messages:
  File "/usr/local/lib/python3.8/site-packages/imbox/messages.py", line 55, in _fetch_email_list
    yield uid, self._fetch_email(uid)
  File "/usr/local/lib/python3.8/site-packages/imbox/messages.py", line 42, in _fetch_email
    return fetch_email_by_uid(uid=uid,
  File "/usr/local/lib/python3.8/site-packages/imbox/parser.py", line 155, in fetch_email_by_uid
    email_object = parse_email(raw_email, policy=parser_policy)
  File "/usr/local/lib/python3.8/site-packages/imbox/parser.py", line 212, in parse_email
    attachment = parse_attachment(part)
  File "/usr/local/lib/python3.8/site-packages/imbox/parser.py", line 122, in parse_attachment
    filename_parts.insert(int(s_name[1]),value[1:-1] if value.startswith('"') else value)
ValueError: invalid literal for int() with base 10: ''

**Comment by vncaragao** [comment]
I changed the 122th row, inputing fix value, works. But i need help.

**Comment by sangkaka** [comment]
same question, try this code.
the reason is because the filename has ";".
`
...
if content_disposition is not None and not message_part.is_multipart():
    # start
    filename_result = re.findall(r'filename="([^"]*)"', content_disposition)
    if filename_result:
        filename = filename_result[0]
        content_disposition = content_disposition.replace(filename, filename.replace(';', ':'))
    # end
    dispositions = [
        disposition.strip()
        for disposition in content_disposition.split(";")
        if disposition.strip()
    ]
`

**Comment by KenJean** [comment]
This just started happening to me yesterday. if one changes Line 121 in **parser.py** from
```
                        if len(s_name) > 1':
```
to
```
                        if len(s_name) > 1 and s_name[1] != '':
```
then it's good to go.

Hope this helps someone else who stumbles upon this little quirk.


-- KJ
