### ISSUE TITLE
Errors

### ISSUE THREAD

**Issue by graingerkid** [martinrusev/imbox#47]
Getting the follow...

     Traceback (most recent call last):
      File "emailparser.py", line 25, in <module>
        for uid, message in messages_from:
      File "/home/graingerkid/blinky/venv/local/lib/python2.7/site-packages/imbox/__init__.py", line 39, in     fetch_list
        yield (uid, self.fetch_by_uid(uid))
      File "/home/graingerkid/blinky/venv/local/lib/python2.7/site-packages/imbox/__init__.py", line 31, in fetch_by_uid
        email_object = parse_email(raw_email)
      File "/home/graingerkid/blinky/venv/local/lib/python2.7/site-packages/imbox/parser.py", line 144, in parse_email
        attachment = parse_attachment(part)
      File "/home/graingerkid/blinky/venv/local/lib/python2.7/site-packages/imbox/parser.py", line 89, in parse_attachment
        'size': len(file_data),
    TypeError: object of type 'NoneType' has no len()

It looks to be due to the attachments but I wanted to check before trying to fix in case it was something you were aware of or it's something weird I'm doing.

**Comment by graingerkid** [comment]
I also get...

     AttributeError: 'Struct' object has no attribute 'subject'

**Comment by dmth** [comment]
We've also run into this Problem (with imbox 0.6, python3):

file_data is set in line 90
`file_data = message_part.get_payload(decode=True)`

Python Documentation [1] says: 
> If the message is a multipart and the decode flag is True, then None is returned.

When looking into the commits, this issue SHOULD not appear since this commit:
https://github.com/martinrusev/imbox/commit/26fe1c9781d0c7ee18f456395db8f14293b742bc

So we'll move to 0.8 and have a look if this issue still exists.

[1] https://docs.python.org/3.4/library/email.message.html

**Comment by dfrison01** [comment]
Running 0.9.6, sometimes still getting the error "AttributeError: 'Struct' object has no attribute 'subject'". Any advance on that?

**Comment by sebix** [comment]
Does the mail have a subject?

**Comment by dfrison01** [comment]
@sebix running some more tests, the mail sometimes indeed has a "blank" subject. Yet, shouldn't the attribute exist within the object anyway?! With the value being empty string or even None, of course...

**Comment by sebix** [comment]
Strictly speaking, not in the mail itself: https://tools.ietf.org/html/rfc5322#section-3.6

>    The only required header fields are the origination date field and
>    the originator address field(s).  All other header fields are
>    syntactically optional. 

But for usability, this may be feasible :)
