### ISSUE TITLE
Encoding error with Python 3.4

### ISSUE THREAD

**Issue by ogranada** [martinrusev/imbox#52]
I have the next error fetching emails with latin characters:

``` python

Traceback (most recent call last):
  File "imboxsample.py", line 34, in <module>
    for uid, message in all_messages:
  File "C:\Documents and Settings\Usuario UTP\Envs\nucleus\lib\site-packages\imbox\__init__.py", line 48, in fetch_list
    yield (uid, self.fetch_by_uid(uid))
  File "C:\Documents and Settings\Usuario UTP\Envs\nucleus\lib\site-packages\imbox\__init__.py", line 39, in fetch_by_uid
    email_object = parse_email(raw_email)
  File "C:\Documents and Settings\Usuario UTP\Envs\nucleus\lib\site-packages\imbox\parser.py", line 182, in parse_email
    parsed_email[valid_key_name] = decode_mail_header(value)
  File "C:\Documents and Settings\Usuario UTP\Envs\nucleus\lib\site-packages\imbox\parser.py", line 38, in decode_mail_header
    logger.debug("Mail header no. {}: {} encoding {}".format(index, str_decode(text, 'utf-8'), charset))
  File "C:\Documents and Settings\Usuario UTP\Envs\nucleus\lib\site-packages\imbox\utils.py", line 13, in str_decode
    return bytes(value, encoding, errors).decode('utf-8')
TypeError: encoding or errors without a string argument

```

I change the method str_decode by:

``` python
    def str_decode(value='', encoding=None, errors='strict'):
        try:
            return bytes(value, encoding, errors).decode('utf-8')
        except Exception as e:
            value.decode("utf-8")

```

**Comment by wagner-certat** [comment]
I think this can be closed.
