### ISSUE TITLE
error when parsing attachment

### ISSUE THREAD

**Issue by mickeydonkey** [martinrusev/imbox#76]
I am running the example provided by README, My python version is 3.5, on windows platform, here is the  error message, please take a look.

```
Traceback (most recent call last):
  File "C:\Users\**\Miniconda3\lib\base64.py", line 518, in _input_type_check
    m = memoryview(s)
TypeError: memoryview: a bytes-like object is required, not 'str'
The above exception was the direct cause of the following exception:
Traceback (most recent call last):
  File "D:/Project/account-adapter/imbox_downloader.py", line 61, in <module>
    for uid, message in all_messages:
  File "C:\Users\**\Miniconda3\lib\site-packages\imbox\__init__.py", line 50, in fetch_list
    yield (uid, self.fetch_by_uid(uid))
  File "C:\Users\**\Miniconda3\lib\site-packages\imbox\__init__.py", line 41, in fetch_by_uid
    email_object = parse_email(raw_email)
  File "C:\Users\**\Miniconda3\lib\site-packages\imbox\parser.py", line 160, in parse_email
    attachment = parse_attachment(part)
  File "C:\Users\**\Miniconda3\lib\site-packages\imbox\parser.py", line 102, in parse_attachment
    name, value = decode_param(param)
  File "C:\Users\**\Miniconda3\lib\site-packages\imbox\parser.py", line 74, in decode_param
    value = base64.decodestring(code)
  File "C:\Users\**\Miniconda3\lib\base64.py", line 560, in decodestring
    return decodebytes(s)
  File "C:\Users\**\Miniconda3\lib\base64.py", line 552, in decodebytes
    _input_type_check(s)
  File "C:\Users\**\Miniconda3\lib\base64.py", line 521, in _input_type_check
    raise TypeError(msg) from err
TypeError: expected bytes-like object, not str

```

**Comment by tomsux** [comment]
edit parser.py
change `value = base64.decodestring(code)` to `value = base64.decodestring(code.encode())`

http://stackoverflow.com/questions/31144988/base64-encodestring-failing-in-python-3

**Comment by wagner-certat** [comment]
I don't get this error with Python 3.4 and Python 3.5 on Linux, so seems to be a problem on windows only.

**Comment by tomsux** [comment]
i get this error with Python 3.5 on Ubuntu16.10

`  File "/home/demo/.local/lib/python3.5/site-packages/imbox/__init__.py", line 41, in fetch_by_uid
    email_object = parse_email(raw_email)
  File "/home/demo/.local/lib/python3.5/site-packages/imbox/parser.py", line 161, in parse_email
    attachment = parse_attachment(part)
  File "/home/demo/.local/lib/python3.5/site-packages/imbox/parser.py", line 103, in parse_attachment
    name, value = decode_param(param)
  File "/home/demo/.local/lib/python3.5/site-packages/imbox/parser.py", line 74, in decode_param
    value = base64.decodestring(code)
  File "/usr/lib/python3.5/base64.py", line 560, in decodestring
    return decodebytes(s)
  File "/usr/lib/python3.5/base64.py", line 552, in decodebytes
    _input_type_check(s)
  File "/usr/lib/python3.5/base64.py", line 521, in _input_type_check
    raise TypeError(msg) from err
TypeError: expected bytes-like object, not str
`

**Comment by ChurchillDu** [comment]
I got this error python3.9 on win10
```
Traceback (most recent call last):
  File "D:\Code\download_attatchment.py", line 30, in <module>
    for (uid, message) in messages:
  File "D:\Software\Python\lib\site-packages\imbox\messages.py", line 55, in _fetch_email_list
    yield uid, self._fetch_email(uid)
  File "D:\Software\Python\lib\site-packages\imbox\messages.py", line 42, in _fetch_email
    return fetch_email_by_uid(uid=uid,
  File "D:\Software\Python\lib\site-packages\imbox\parser.py", line 155, in fetch_email_by_uid
    email_object = parse_email(raw_email, policy=parser_policy)
  File "D:\Software\Python\lib\site-packages\imbox\parser.py", line 212, in parse_email
    attachment = parse_attachment(part)
  File "D:\Software\Python\lib\site-packages\imbox\parser.py", line 115, in parse_attachment
    name, value = decode_param(param)
  File "D:\Software\Python\lib\site-packages\imbox\parser.py", line 80, in decode_param
    value = base64.decodebytes(code.encode())
  File "D:\Software\Python\lib\base64.py", line 538, in decodebytes
    return binascii.a2b_base64(s)
binascii.Error: Invalid base64-encoded string: number of data characters (109) cannot be 1 more than a multiple of 4
```

**Comment by wagner-certat** [comment]
@ChurchillDu please open a new issue. The old one is four years old, not the same issue as yours (the error message is different) and this issue here was already fixed.
